services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bd_pisid
      TZ: "Europe/Lisbon"
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
      TZ: "Europe/Lisbon"
    depends_on:
      - mysql

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: pisid_maze
      TZ: "Europe/Lisbon"
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    container_name: pisid_php
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./web:/var/www/html
    depends_on:
      - mysql
    environment:
      TZ: "Europe/Lisbon"

volumes:
  mongo_data: